services:
  app:
    image: 'mktplace-postgres-app'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mktplace-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/buysell
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123091991

  db:
    image: 'postgres:16.0'
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123091991
      POSTGRES_DB: buysell
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $postgres -d $buysell"]
      interval: 10s
      timeout: 5s
      retries: 5

  volumes:
    db-data:
